---
baseURL: https://forestry.ryandejaegher.com/
languageCode: en-us
# The Site Title
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
# Changes the URL structure
permalinks:
  post: /:title/
  tags: /:slug/
  squarespace: /:title/

  
disqusShortname: ryan_dejaegher  
# Adss custom Menu
menu:
  main:
  - identifier: start-here
    name: Start Here
    title: Start Here
    url: /start-here/
    weight: 1
  
  - identifier: squarespace
    name: Squarespace
    title: Squarespace
    url: /squarespace/
    weight: 2

paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series

