# Theme settings
---
baseURL: https://example.com
languageCode: en-us
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
menu:
  main:
  - identifier: blog
    name: This is the blog section
    title: blog section
    url: /blog/
    weight: -110
