---
baseURL: https://example.com
languageCode: en-us
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
permalinks:
  posts: /:title/
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
