---
baseURL: https://ryandejaegher.com/
languageCode: en-us
DefaultContentLangage: en
enableRobotsTXT: true
canonifyURLs: true
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
permalinks:
  pages: "/:title/"
  articles: "/:title/"
disqusShortname: ryandejaegher
# menu:
#   main:
#   - url: https://apple.com
#     name: Wow
#     weight: 3
#   - url: "/squarespace-tutorials"
#     name: Squarespace Tutorials
#     title: Squarespace Tutorials
#     weight: 1
#     identifier: squarespace-tutorials
#   - url: "/articles/"
#     name: Articles
#     title: Articles
#     weight: 2
#     identifier: articles
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
enableInlineShortcodes: true
enableGitInfo: true
params:
  author: Ryan Dejaegher
  twitterHandle: "@ryandejaegher"
  description: Web Developer · Web Designer
  sitename: Ryan Dejaegher
  tagline: Web Developer · Web Designer
  og_image: 
  debugGrid: false
  addNovelaScripts: false
  addSnipcart: false
  siteDebug: true
  mainSections:
  - thoughts
  mainCategories:
  - squarespace
imaging:
  quality: 90
paginate: 10
sitemap:
  ChangeFreq: weekly
  Priority: 0.7
social:
  twitter: https://twitter.com/ryandejaegher
  github: https://github.com/ryandejaegher
  linkedin: ''
  youtube: https://www.youtube.com/channel/UCsg_D6VRajsl7FoD6rrI89w/
  dribbble: https://dribbble.com/ryandejaegher
  instagram: ''
  facebook: https://www.facebook.com/dejaegherryan/
taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series
log: true
logFile: hugo.log
verboseLog: true
