---
baseURL: https://ryandejaegher.com/
languageCode: en-us
DefaultContentLangage: en

enableRobotsTXT: true
canonifyURLs: true

# The Site Title
title: Ryan Dejaegher

pygmentsstyle: monokai
theme: novela

# Changes the URL structure
permalinks:
  pages: /:title/
  squarespace-tutorials: /:title/
  categories: /:title/
  articles: /:title/



# Adds Disqus
disqusShortname: ryandejaegher

# Adds custom Menu
menu:
  main:
  - identifier: Start Here
    name: Start Here
    title: Start Here
    url: /start-here
    weight: 1
  - identifier: articles
    name: Articles
    title: Articles
    url: /articles/
    weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

enableInlineShortcodes: true
      
params:
  author: "Ryan Dejaegher"
  twitterHandle: "@ryandejaegher"
  description: "Web Developer · Web Designer"
  sitename: Ryan Dejaegher
  tagline: "Web Developer · Web Designer"
  og_image:
  debugGrid: false
  addNovelaScripts: false
  addSnipcart: false
  siteDebug: true
  mainSections: 
    - squarespace-tutorials
    - thoughts
  mainCategories:
    - squarespace

imaging:
  quality: 90

paginate: 10

sitemap:
  ChangeFreq: weekly
  Priority: .7

social:
  twitter: "https://twitter.com/ryandejaegher"
  github: 'https://github.com/ryandejaegher'
  linkedin: ''
  youtube: 'https://www.youtube.com/channel/UCsg_D6VRajsl7FoD6rrI89w/'
  dribbble: 'https://dribbble.com/ryandejaegher'
  instagram: ''
  facebook: 'https://www.facebook.com/dejaegherryan/'

taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series

log: true
logFile: "hugo.log"
verboseLog: true