---
baseURL: https://ryandejaegher.com/
languageCode: en-us
# The Site Title
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
# Changes the URL structure
permalinks:
  post: /:title/
  tags: /:slug/
  squarespace: /:title/

# Adds Disqus
disqusShortname: ryandejaegher

# Adds custom Menu
menu:
  main:
  - identifier: start-here
    name: Start Here
    title: Start Here
    url: /start-here/
    weight: 1
  
  - identifier: squarespace
    name: Squarespace
    title: Squarespace
    url: /squarespace/
    weight: 2

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

enableInlineShortcodes: true
      
params:
  sitePadding: "px-20"
paginate: 10
social:
  twitter: https://twitter.com/ryandejaegher
  github: https://github.com/ryandejaegher
  linkedin: ''
  youtube: 'https://www.youtube.com/channel/UCsg_D6VRajsl7FoD6rrI89w/'
  dribbble: 'https://dribbble.com/ryandejaegher'
  instagram: ''
  facebook: 'https://www.facebook.com/dejaegherryan/'
taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series

