---
baseURL: https://forestry.ryandejaegher.com
languageCode: en-us
# The Site Title
title: Ryan Dejaegher
pygmentsstyle: monokai
theme: novela
# Changes the URL structure
permalinks:
  post: /:title/
sectionPagesMenu: mainmenu
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
  tag: tags
  category: categories
  series: series

