baseURL: "https://example.com"
languageCode: "en-us"
title: "Ryan Dejaegher"
pygmentsstyle: 'monokai'
permalinks:
  posts: /:title/
sectionPagesMenu: "mainmenu"

menu
  -menu.mainmenu
  identifier: "home"
  name: "Home"
  url: "/"
  weight: 1



