title: Example Button
context:
    text: Primary Button
    is-enabled: true
    class: bg-indigo-400
variants:
- name: warning
  context:
    modifier: alert
    text: Cancel
    class: bg-red-400
- name: success
  context:
    modifier: success
    text: Success
    class: bg-teal-400
